development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:ae024c82ff6a3534054c8798b1c21813@soldierfish.redistogo.com:10644/
  channel_prefix: black_jack_production
